#!/bin/bash
# 
# 06/02/14: added support to links, absolute paths and error-code propagation
# 05/02/14: persistent-run checks wheter or not files have changed before executing a command or script
#
# author: Wilker Aziz

# help message
usage()
{
cat << EOF
usage: $0 options

OPTIONS:
    -h  show this message
    -t  target(s) (comma-separated list)
    -c  command
    -s  script (path)
    -v  verbose

    Runs a command and/or script. 
    If targets are set, execution only happens if at least one target is not persisted.
    If both -c and -s are set, -c is executed first.
    A target may not be available before -c and -s are executed, but it must
    be available after, otherwise $0 produces an error.

    Exit status:
        0   success
        1   bad argument
        10  target unavailable
EOF
}

# auxiliary
echoerr() { echo "$@" 1>&2; }
echolog() 
{ 
    if [[ $verbose == 1 ]]; then 
        echo "$@" 1>&2
    fi
}

# variables
targets=
command=
script=
verbose=

# argparse
while getopts "ht:c:s:v" OPTION
do
    case $OPTION in
        h)
            usage
            exit 1
            ;;
        t)
            targets=$(echo $OPTARG | tr "," "\n")
            ;;
        c)
            command=$OPTARG
            ;;
        s)
            script=$OPTARG
            if [ ! -f $script ]; then
                echoerr "File not found: $script"
                exit 1
            fi
            ;;
        v)
            verbose=1
            ;;
        ?)
        usage
        exit
        ;;
    esac
done

# sanity check
if [[ -z $command && -z $script ]]; then
    echoerr "requires -c or -s"
    exit 1
fi

# persistency step
run=
update=0
if [ -z $targets ]; then
    run=1
else
    for tgt in $targets; do
        dir=`dirname "$tgt"`
        base=`basename "$tgt"`
        token="$dir/.$base.persrun"
        echolog "Checking: $tgt"
        if [ ! -e "$tgt" ]; then
            echolog " '$tgt' does not exist"
            run=1
            update=1
        elif [ ! -e $token ]; then
            echolog " '$token' does not exist"
            run=1
            update=1
        else
            status=`diff -q $token <(stat -L -c%y $tgt)`
            if [ ! -z "$status" ]; then
                echolog " '$tgt' changed since last run"
                run=1
                update=1
            else
                echolog " [passed]"
            fi
        fi
    done
fi

error=0
if [ -z $run ]; then
    echolog "Nothing to run."
    exit 0
else
    # run command
    if [[ ! -z $command ]]; then
        echolog "Running: $command"
        eval $command
        error=$?
    fi

    # run script
    if [[ $error == 0 && ! -z $script ]]; then
        echolog "Running: $script"
        bash $script
        serror=$?
    fi

fi

if [[ $error == 0 ]]; then
    # update stamps
    if [[ $update != 0 ]]; then
        for tgt in $targets; do
            if [ ! -f $tgt ]; then
                error=10
                echoerr "ERROR: target unavailable '$tgt'"
            else
                dir=`dirname "$tgt"`
                base=`basename "$tgt"`
                token="$dir/.$base.persrun"
                echolog "Updating timestamp: stat -L -c%y $tgt > $token"
                stat -L -c%y $tgt > $token
            fi
        done
    fi
fi

exit $error
